#端口号
server:
  port: 80

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql:///hotel?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10

mybatis:
  #mapper文件位置
  mapper-locations: classpath:mapper/*.xml
  #别名配置
  type-aliases-package: cn.edu.tyut.pojo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
